name: Keyfactor Release Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize, edited, reopened]
  push:
  create:
    branches:
      - 'release-*.*'

jobs:
  call-starter-workflow:
    uses: keyfactor/actions/.github/workflows/starter.yml@d75ddd58537af8e5b6961b6e571a09ecd751c5b5 # v3.0
    secrets:
      token: ${{ secrets.V2BUILDTOKEN}}
      APPROVE_README_PUSH: ${{ secrets.APPROVE_README_PUSH}}
      gpg_key: ${{ secrets.KF_GPG_PRIVATE_KEY }}
      gpg_pass: ${{ secrets.KF_GPG_PASSPHRASE }}
      scan_token: ${{ secrets.SAST_TOKEN }}
      docker-user: ${{ secrets.DOCKER_USER }}
      docker-token:  ${{ secrets.DOCKER_PWD }}
